// Generated by gencpp from file zigbee/GPS.msg
// DO NOT EDIT!


#ifndef ZIGBEE_MESSAGE_GPS_H
#define ZIGBEE_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zigbee
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : ID(0)
    , ts(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : ID(0)
    , ts(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _ID_type;
  _ID_type ID;

   typedef int32_t _ts_type;
  _ts_type ts;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;




  typedef boost::shared_ptr< ::zigbee::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zigbee::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::zigbee::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::zigbee::GPS > GPSPtr;
typedef boost::shared_ptr< ::zigbee::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zigbee::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zigbee::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zigbee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'zigbee': ['/home/twei/catkin_ws/src/zigbee/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zigbee::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "287b2305f7c892f3b2615e8bbc5d8db7";
  }

  static const char* value(const ::zigbee::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x287b2305f7c892f3ULL;
  static const uint64_t static_value2 = 0xb2615e8bbc5d8db7ULL;
};

template<class ContainerAllocator>
struct DataType< ::zigbee::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zigbee/GPS";
  }

  static const char* value(const ::zigbee::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zigbee::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ID\n\
\n\
int32 ts\n\
\n\
#location is in angle\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
";
  }

  static const char* value(const ::zigbee::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zigbee::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.ts);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zigbee::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zigbee::GPS_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "ts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ts);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZIGBEE_MESSAGE_GPS_H
