// Generated by gencpp from file zigbee/Posi.msg
// DO NOT EDIT!


#ifndef ZIGBEE_MESSAGE_POSI_H
#define ZIGBEE_MESSAGE_POSI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zigbee
{
template <class ContainerAllocator>
struct Posi_
{
  typedef Posi_<ContainerAllocator> Type;

  Posi_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , fi(0.0)  {
    }
  Posi_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , fi(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _fi_type;
  _fi_type fi;




  typedef boost::shared_ptr< ::zigbee::Posi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zigbee::Posi_<ContainerAllocator> const> ConstPtr;

}; // struct Posi_

typedef ::zigbee::Posi_<std::allocator<void> > Posi;

typedef boost::shared_ptr< ::zigbee::Posi > PosiPtr;
typedef boost::shared_ptr< ::zigbee::Posi const> PosiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zigbee::Posi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zigbee::Posi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zigbee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'zigbee': ['/home/twei/catkin_ws/src/zigbee/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::Posi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::Posi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::Posi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::Posi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::Posi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::Posi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zigbee::Posi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7f9bc2b116f9a0efd4cf9e3a0c5a2a0";
  }

  static const char* value(const ::zigbee::Posi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7f9bc2b116f9a0eULL;
  static const uint64_t static_value2 = 0xfd4cf9e3a0c5a2a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::zigbee::Posi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zigbee/Posi";
  }

  static const char* value(const ::zigbee::Posi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zigbee::Posi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 fi\n\
";
  }

  static const char* value(const ::zigbee::Posi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zigbee::Posi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.fi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Posi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zigbee::Posi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zigbee::Posi_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "fi: ";
    Printer<float>::stream(s, indent + "  ", v.fi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZIGBEE_MESSAGE_POSI_H
