// Generated by gencpp from file zigbee/ShapeConfig.msg
// DO NOT EDIT!


#ifndef ZIGBEE_MESSAGE_SHAPECONFIG_H
#define ZIGBEE_MESSAGE_SHAPECONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zigbee
{
template <class ContainerAllocator>
struct ShapeConfig_
{
  typedef ShapeConfig_<ContainerAllocator> Type;

  ShapeConfig_()
    : i(0)
    , j(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , fi(0.0)
    , totol_uav_num(0)  {
    }
  ShapeConfig_(const ContainerAllocator& _alloc)
    : i(0)
    , j(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , fi(0.0)
    , totol_uav_num(0)  {
  (void)_alloc;
    }



   typedef int8_t _i_type;
  _i_type i;

   typedef int8_t _j_type;
  _j_type j;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _fi_type;
  _fi_type fi;

   typedef int8_t _totol_uav_num_type;
  _totol_uav_num_type totol_uav_num;




  typedef boost::shared_ptr< ::zigbee::ShapeConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zigbee::ShapeConfig_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeConfig_

typedef ::zigbee::ShapeConfig_<std::allocator<void> > ShapeConfig;

typedef boost::shared_ptr< ::zigbee::ShapeConfig > ShapeConfigPtr;
typedef boost::shared_ptr< ::zigbee::ShapeConfig const> ShapeConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zigbee::ShapeConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zigbee::ShapeConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zigbee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'zigbee': ['/home/twei/catkin_ws/src/zigbee/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::ShapeConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zigbee::ShapeConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::ShapeConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zigbee::ShapeConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::ShapeConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zigbee::ShapeConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zigbee::ShapeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d3f4265dd95f24062ec4610cecbb8e6";
  }

  static const char* value(const ::zigbee::ShapeConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d3f4265dd95f240ULL;
  static const uint64_t static_value2 = 0x62ec4610cecbb8e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::zigbee::ShapeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zigbee/ShapeConfig";
  }

  static const char* value(const ::zigbee::ShapeConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zigbee::ShapeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "byte i\n\
byte j\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 fi\n\
\n\
byte totol_uav_num\n\
";
  }

  static const char* value(const ::zigbee::ShapeConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zigbee::ShapeConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i);
      stream.next(m.j);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.fi);
      stream.next(m.totol_uav_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zigbee::ShapeConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zigbee::ShapeConfig_<ContainerAllocator>& v)
  {
    s << indent << "i: ";
    Printer<int8_t>::stream(s, indent + "  ", v.i);
    s << indent << "j: ";
    Printer<int8_t>::stream(s, indent + "  ", v.j);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "fi: ";
    Printer<float>::stream(s, indent + "  ", v.fi);
    s << indent << "totol_uav_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.totol_uav_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZIGBEE_MESSAGE_SHAPECONFIG_H
